### ISSUE TITLE
mpv_get_property get stuck in qtexample

### ISSUE THREAD

**Issue by lcdtyph** [mpv-player/mpv-examples#11]
Hi all,

I'm using qt5.9 and the latest mpv on macos 10.13.

I've found that `mpv_get_property' would get stuck in [here](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/qt/qtexample.cpp#L140).
Could you please help me to avoid this? .. I've being searching google for days...

BTW, `mpv_get_property_async' works fine in this example.

**Comment by wm4** [comment]
Can you show a debugger backtrace for this or so? It shouldn't freeze.

**Comment by liberize** [comment]
Same here. macOS 10.12.6.

1  __psynch_cvwait                                                                                                                                                                  0x7fffad528bf2 
2  _pthread_cond_wait                                                                                                                                                               0x7fffad6147fa 
3  mp_dispatch_lock                                                                                                                                                                 0x1000fa4cd    
4  mpv_get_property                                                                                                                                                                 0x100110db5    
5  MainWindow::handle_mpv_event(mpv_event *)                                                                                                                 qtexample.cpp      140 0x1000059a7    
6  MainWindow::on_mpv_events()                                                                                                                               qtexample.cpp      180 0x100004e56    
7  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (MainWindow:: *)()>::call(void (MainWindow:: *)(), MainWindow *, void * *) qobjectdefs_impl.h 134 0x10000a6be    
8  void QtPrivate::FunctionPointer<void (MainWindow:: *)()>::call<QtPrivate::List<>, void>(void (MainWindow:: *)(), MainWindow *, void * *)                  qobjectdefs_impl.h 167 0x10000a613    
9  QtPrivate::QSlotObject<void (MainWindow:: *)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *)            qobjectdefs_impl.h 396 0x10000a4e6    
10 QObject::event(QEvent *)                                                                                                                                                         0x1010ecf11    
11 QWidget::event(QEvent *)                                                                                                                                                         0x100486a46    
12 QMainWindow::event(QEvent *)                                                                                                                                                     0x100594845    
13 QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                          0x10044a8bd    
14 QApplication::notify(QObject *, QEvent *)                                                                                                                                        0x10044bd0c    
15 QCoreApplication::notifyInternal2(QObject *, QEvent *)                                                                                                                           0x1010c3d68    
16 QCoreApplicationPrivate::sendPostedEvents(QObject *, int, QThreadData *)                                                                                                         0x1010c4f08    
17 ___lldb_unnamed_symbol563$$libqcocoa.dylib                                                                                                                                       0x106ae28f7    
18 ___lldb_unnamed_symbol575$$libqcocoa.dylib                                                                                                                                       0x106ae31c1    
19 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__                                                                                                                       0x7fff97c92321 
20 __CFRunLoopDoSources0                                                                                                                                                            0x7fff97c7321d 
21 __CFRunLoopRun                                                                                                                                                                   0x7fff97c72716 
22 CFRunLoopRunSpecific                                                                                                                                                             0x7fff97c72114 
23 RunCurrentEventLoopInMode                                                                                                                                                        0x7fff971d2ebc 
24 ReceiveNextEventCommon                                                                                                                                                           0x7fff971d2cf1 
25 _BlockUntilNextEventMatchingListInModeWithFilter                                                                                                                                 0x7fff971d2b26 
26 _DPSNextEvent                                                                                                                                                                    0x7fff95769a54 
27 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]                                                                                                  0x7fff95ee57ee 
28 -[NSApplication run]                                                                                                                                                             0x7fff9575e3db 
29 ___lldb_unnamed_symbol556$$libqcocoa.dylib                                                                                                                                       0x106ae1fad    
30 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                          0x1010bf8ee    
31 QCoreApplication::exec()                                                                                                                                                         0x1010c4461    
32 main                                                                                                                                                      qtexample.cpp      224 0x10000728e    
33 start                                                                                                                                                                            0x7fffad3fa235

**Comment by wm4** [comment]
If this still an issue, make an issue on the mpv main repo.

**Comment by anohren** [comment]
Is this tracked in the main repo? Mpv is deadlocking all the time in [3rd party project](https://github.com/iina/iina/issues/2149), just wanted to know if it's on mpv's side.

**Comment by wm4** [comment]
I'm not aware of such issues. Nor am I familiar with the inner workings of iina. The issue you linked hints that it's something in the render API. This is quite fragile, and I just found some potential deadlock bugs today.

They should make sure to adhere all of the following: https://github.com/mpv-player/mpv/blob/master/libmpv/render.h#L54

Note how enabling advanced rendering control disallows the API user from calling certain "blocking" functions from the same thread as the rendering functions.

The last items in that list are the issues I found today. So try to disable DR by setting vd-lavc-dr=no. Maybe you actually hit exactly that case. That would actually be nice, a bug hat can be fixed and has known reproduction is better than a theoretical bug that might cause undetected problems.

In any case, they should make an issue on the main repository, preferably with reproduction. Unfortunately I don't have a modern mac available, so I can't try to reproduce it with iina.

**Comment by anohren** [comment]
Thanks for your input. The code seems to call `mpv_get_property_string`, i.e. `mpv_get_property`, from a render thread. That function is not marked "Safe to be called from mpv render API threads", so maybe that's it.

**Comment by wm4** [comment]
Yes, certainly that's it. We just found out today that mpv's Swift backend has a similar issue (but easy to fix according to the author).

Recent git master also fixes these DR potential deadlock issues I mentioned.

**Comment by anohren** [comment]
Disabling advanced rendering control solved it immediately. Thanks for pointing me to the right part of the doc, otherwise it would probably have taken much longer for me to understand what was the cause. I hadn't looked at the mpv parts before.

I enjoyed reading your commit messages. Made me think of the last panel in https://i1.wp.com/abstrusegoose.com/strips/you_down_wit_OPC-yeah_you_know_me.png

**Comment by Akemi** [comment]
though keep in mind, just disabling advanced rendering is not a solution to the problem. it's just not fatal anymore, but still is a problem. better to use the async methods or use an observe and keep track of the needed properties yourself.

**Comment by wm4** [comment]
I pondered whether libmpv could be changed to accept such "reentrant" calls. The whole issue is that any libmpv API function, such as mpv_get_property, may wait for the user's render API thread. If the code knew that it's on the render API thread, it could just access the GL state directly (instead of waiting until the render API thread wakes up and runs mpv_render_context_update()). This would remove the deadlock.

Unfortunately, libmpv API functions don't know whether they're on the render thread. A thread is just a thread, you don't know whether the API user intends it to be the render thread.

Changing this would require additional user API, maybe something like this:
```
// Tell libmpv that we're currently on the render thread (OpenGL can be accessed etc.)
// This has to be called once on the thread where the GL context lives.
// Things could get trickier depending on API user requirements.
mpv_render_thread_enter(render_ctx);

...

// Run something on the render thread. If the core wants to access 
// the render thread right now, this would not deadlock.
mpv_get_property(ctx, ...);
```
Or it could be a user callback that checks whether the current thread has the GL context, or a function to set a thread handle. Maybe one could say that mpv_render_context_create() "pins" it on the thread where it was called, but I don't like that much.

If anyone thinks this would be a good change, then let me know. It would still require complex changes to the libmpv core (and video timing, oddly). I don't know yet whether it'll work out, so I better won't try to put effort into it unless someone thinks it's absolutely needed. I also don't know if this thread is reaching any actual API user.


> Made me think of the last panel in https://i1.wp.com/abstrusegoose.com/strips/you_down_wit_OPC-yeah_you_know_me.png

The same happens with my own code.

**Comment by wm4** [comment]
PS: the recommended use of the render API is to run rendering in a separate thread. That would remove all these issues as well. Originally I wrote the render API (aka opengl-cb) for something that _required_ rendering to be on a different thread from application logic, so none of this was really an issue. Although the SDL example proves that everything can run on 1 thread just fine, if you take the restrictions into consideration.

**Comment by Akemi** [comment]
just some infos regarding the CAOpenGLLAyer that one should use on macOS. you can render on a separate thread, but not in all cases. there are some, one can't control, that force rendering on the main thread. some of these are asynchronous rendering or specific system events that force a redraw of the window/view/etc.

also on a side note, when using a dispatch queue for rendering, one has to keep in mind that a dispatch queue is a pool of threads and rendering could switch between different threads. which is also the case in cocoa-cb within mpv. this can obviously worked around, see https://github.com/mpv-player/mpv/pull/6352 and https://github.com/Akemi/macos_precise_timing_tests as an example and pointers.

**Comment by anohren** [comment]
> though keep in mind, just disabling advanced rendering is not a solution to the problem. it's just not fatal anymore, but still is a problem. better to use the async methods or use an observe and keep track of the needed properties yourself.

Thanks, I got that impression too after reading. I wrote an asynchronous wrapper just to experiment, and it did solve the deadlock -- at that call site. Unfortunately that app is entrenched in synchronous calls so it just relocated the problem. 

Until they are more prepared for PRs I'll just eat the performance hit instead, and let someone with a greater need do the heavy rewrite.

> you can render on a separate thread, but not in all cases. there are some, one can't control, that force rendering on the main thread

What are the implications of these forced renders? That it's always incorrect API usage to call `mpv_get_property` on the main thread when using CAOpenGLLayer? Sorry, haven't really looked in-depth at IINA's use of mpv. From what I can tell it mostly calls `mpv_render_context_render` on a private queue, but also from the main queue on special occasions. 

I don't really know what `cocoa-cb` is since I couldn't find a descriptive comment or readme, nor do I know how to interpret the directory structure in the mpv repo (I generally had a hard time identifying the purpose of the components). Maybe I looked in the wrong places.

**Comment by wm4** [comment]
cocoa-cb is just the mpv-internal swift backend. It also uses the libmpv render API.

**Comment by Akemi** [comment]
> What are the implications of these forced renders? That it's always incorrect API usage to call mpv_get_property on the main thread when using CAOpenGLLayer? Sorry, haven't really looked in-depth at IINA's use of mpv. From what I can tell it mostly calls mpv_render_context_render on a private queue, but also from the main queue on special occasions.

potential yes.
