### ISSUE TITLE
tuning mpv-examples qt_opengl

### ISSUE THREAD

**Issue by Xuno** [mpv-player/mpv-examples#2]
Code from mpv-examples/libmpv/qt_opengl/mpvwidget.cpp does not find all OpenGL functions.

Modifications based on code from https://github.com/plexinc/plex-media-player/blob/master/src/player/PlayerQuickItem.cpp#L104 fixes the problem.

```
static void *get_proc_address(void *ctx, const char *name) {
    Q_UNUSED(ctx);
    QOpenGLContext* glctx = QOpenGLContext::currentContext();
    if (!glctx)
        return NULL;
    void *res = (void *)glctx->getProcAddress(QByteArray(name));
#ifdef Q_OS_WIN32
    if (!res)
    {
        HMODULE handle = (HMODULE)QOpenGLContext::openGLModuleHandle();
        if (handle)
            res = (void *)GetProcAddress(handle, name);
    }
#endif
    return res;
}
```

It works under Qt5. Tested on Qt 5.5, Qt 5.6. OS Windows 10 x64.

**Comment by wm4** [comment]
Didn't they fix this in Qt 5.6?
