### ISSUE TITLE
qt_opengl resize laggy on macOS

### ISSUE THREAD

**Issue by liberize** [mpv-player/mpv-examples#24]
It's very laggy when I resize the window, almost only respond after I stop moving my mouse.
Switch to new render api doesn't solve the problem.
IINA is pretty smooth, they use opengl-cb as well, no idea why.
Is this a qt problem or mpv problem?
Tried with qt 5.11 on macOS 10.12 and 10.13.

**Comment by liberize** [comment]
@Akemi Can you help me?

**Comment by Akemi** [comment]
it's most likely a problem of that example. probably blocking the rending when resizing in some way. i never looked at the qt examples so i can't say anything specific.

**Comment by liberize** [comment]
I tried to wrap a NSView with QMacCocoaViewContainer and render video to the NSView, like what IINA did. The problem is gone. Obviously it's a qt problem.

**Comment by jurplel** [comment]
try setting the "video-timing-offset" option to 0

**Comment by wm4** [comment]
Can't be helped.
