### ISSUE TITLE
[Enhancement] Provide CSharp example for Opengl

### ISSUE THREAD

**Issue by wjax** [mpv-player/mpv-examples#25]
Using libmpv with window integration in wpf is a pain due to Airspace issues. 
Mouse cliks and events can be redirected with some work but the mpv ontop of everything else in the wpf app is impossible to avoid.

So I would like to follow the opengl path but I do not have a clue of how to start. 

It would be really nice if some dev could give us a list of the steps to follow (or even a full example!!)

Many thanks

**Comment by wjax** [comment]
Nobody?

I am willing to code and generate the csharp with OpenGL example. Just need some basic guidance

**Comment by wjax** [comment]
Hello.

Thanks for the answer.
I have been all day studying it and there is almost everything I need. However one thing is missing.

The example from starz0r is based on UWP and not WPF Desktop app. It uses a SwapChainPanel which is not available in WPF Desktop apps. Without that, there is no HWND and no way to call eglCreateWindowSurface.

So I am stuck in there. Any ideas?

Using a WinFormHost to host a panel and get its HWND is not an option as I would be in the same situation as with libmpv to window => Airspace issues.

**Comment by wjax** [comment]
I think there would be a lot of people interested in mpv for wpf with both performance and correct airspace.

If anyone is willing to help me I would put the coding force, but I need guidance

**Comment by wm4** [comment]
This thing apparently uses libmpv+WPF: https://github.com/stax76/mpv.net
