### ISSUE TITLE
How to play several RTSP streams int the same time according to the example of qt-opengl?

### ISSUE THREAD

**Issue by yarafa** [mpv-player/mpv-examples#31]
As the title described, I add another [MpvWidget](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/qt_opengl/mpvwidget.h) to the MainWidget and set load command to each of MpvWidget, but I get the result as the picture shownd below.
![无标题](https://user-images.githubusercontent.com/45851564/83985213-d564c500-a96a-11ea-8be7-bf3a4293f54a.png)

In the picture, actually, the left MpvWidget is now playing the video of the right one, and the right MpvWidget does not play anything. Here is my code.

`MainWidget::MainWidget(QWidget *parent) : QWidget(parent) {

    MpvWidget *player = new MpvWidget(this, 1);
    player->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);

    QGridLayout *layout = new QGridLayout();
    layout->setMargin(0);
    layout->setSpacing(1);
    setLayout(layout);

    layout->addWidget(player, 0, 0, 1, 1);

    QString file = "rtsp://192.168.31.111:10020/proxy/3";
    player->command(QStringList() << "loadfile" << file);

    MpvWidget *player2 = new MpvWidget(this, 2);
    player2->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
    layout->addWidget(player2, 0, 1, 1, 1);

    QString file2 = "rtsp://192.168.31.253:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream";
    player->command(QStringList() << "loadfile" << file2);

}`

Any idea is appreciated

**Comment by CounterPillow** [comment]
>`player->command(QStringList() << "loadfile" << file2);`

You're sending the loadfile command for the second player to the first player.

**Comment by yarafa** [comment]
@CounterPillow What a big mistake. Thanks very much!
