### ISSUE TITLE
Playing videos are strange on samsung phones

### ISSUE THREAD

**Issue by fifa87** [mpv-player/mpv-examples#33]
I have built QT project using your example on android.

I used this recent libraries built by using the following github,
https://github.com/mpv-android/mpv-android
But on all new Samsung phones(Android 9-10) and few phones playing video is strange.
most Other phones are ok.
Please look at this link video.
https://drive.google.com/file/d/1R5OYsI3rvXPhp0Ppj32Y2K16VCvbe0Ht/view?usp=sharing
are there anyone to help?

I used this options
    mpvSetProperty("hwdec", "auto-safe");
    mpvSetProperty("interpolation", "yes");
    mpvSetProperty("video-sync", "audio");
    mpvSetProperty("vo", "libmpv");

I used Qt.5.14.2. libmpv for android is recent on above github.
This is very urgent. please help me.
Best Regards.

**Comment by tmm1** [comment]
Please do not cross post.

**Comment by fifa87** [comment]
How are you? Thank you for your response for my issue.
But i can't understand what do you mean.
Can't i post this issue?
Best Regards.


On 6/19/2020 09:11，Aman Gupta Karmani<notifications@github.com> wrote：

Please do not cross post.

**Comment by tmm1** [comment]
You already posted it here: https://github.com/mpv-android/mpv-android/issues/280

One time is enough.

**Comment by fifa87** [comment]
Oh, are those same source? I understand.
But i will be thanks you can help me to resolve my issue soon.
It is very urgent.
Thank you.
Best Regards.


On 6/19/2020 09:27，Aman Gupta Karmani<notifications@github.com> wrote：

You already posted it here: mpv-android/mpv-android#280

One time is enough.
