### ISSUE TITLE
Swift Example on macOS?

### ISSUE THREAD

**Issue by 1c7** [mpv-player/mpv-examples#37]

**Comment by Akemi** [comment]
https://github.com/Akemi/libmpv-objc-swift
https://github.com/Akemi/libmpv-CAOpenGLLayer-test

or just straight from the mpv directly the cocoa-cb backend.

**Comment by 1c7** [comment]
@Akemi Thank you!

**Comment by lionel008** [comment]
> https://github.com/Akemi/libmpv-objc-swift https://github.com/Akemi/libmpv-CAOpenGLLayer-test
> 
> or just straight from the mpv directly the cocoa-cb backend.

Hi @Akemi can you provide your email? want to discuss about more mpv example?
