### ISSUE TITLE
update api examples from opengl-cb API to render API

### ISSUE THREAD

**Issue by c1ngular** [mpv-player/mpv-examples#38]
could you please update examples to newest API , it would be very useful for starters like me ,
thank you

**Comment by Akemi** [comment]
that's very unspecific. there are a bunch of examples for the current render API. here are few examples of updated examples/commits.

https://github.com/mpv-player/mpv-examples/commit/b51d901b79d1b8b433ad22fca91ea44e45096887
https://github.com/mpv-player/mpv-examples/commit/a543d81bb31176a1ace95c1ea53d378e569a47db
https://github.com/mpv-player/mpv-examples/commit/ea84bfbb96f3c9d4857ac9558e1a9de913d43df1
https://github.com/mpv-player/mpv-examples/commit/e5553b705b7355f513ff0cf892523a3799b5b41a

**Comment by wm4** [comment]
Looks like these are the only examples left that use the old API?
https://github.com/mpv-player/mpv-examples/blob/master/libmpv/qml_direct/main.cpp
https://github.com/mpv-player/mpv-examples/blob/master/libmpv/wxwidgets_opengl/main.cpp

**Comment by wm4** [comment]
Oh, and ios.

**Comment by wm4** [comment]
Well, after all, it's too much work. I removed them to avoid confusing new developers. I've also disabled the opengl_cb API in mpv git master (and the next release) to avoid that the API somehow keeps sticking around.
