### ISSUE TITLE
multiple videos playback in same window 

### ISSUE THREAD

**Issue by c1ngular** [mpv-player/mpv-examples#39]
i am using mpv qml , it is working perfect .
how can i playback several videos simultaneously from same window , for now , a new window just pop up above the current window everytime i tried to add a new one(player) . 

thank you

**Comment by wm4** [comment]
You can easily adapt the qml example in this repository for this. Create multiple mpv instances with associated MpvRenderer, place them as you like. mpv itself has no support for simultaneous videos (although there's a rather inefficient way to stack multiple video streams with --lavfi-complex).

**Comment by c1ngular** [comment]
@wm4  that is what i did , i am using a qml listview to playback multiple streaming videos(rtmp/rtsp), it is working pretty good in same window , until i add a local video file to the video listview , it pops up and play video in new window , any idea ?

**Comment by wm4** [comment]
Hard to tell without more information, such as logs. Remote/local shouldn't make a difference at all.
