### ISSUE TITLE
The `simple.c` doesn't work

### ISSUE THREAD

**Issue by 1c7** [mpv-player/mpv-examples#40]
## Link
https://github.com/mpv-player/mpv-examples/blob/master/libmpv/simple/simple.c

![image](https://user-images.githubusercontent.com/1804755/97088371-e0429c80-1662-11eb-8027-042e81bb4f07.png)
![image](https://user-images.githubusercontent.com/1804755/97088376-e8024100-1662-11eb-8315-50cbdd9706b1.png)

## First, The compile command works fine on macOS
```
gcc -o simple simple.c `pkg-config --libs --cflags mpv`
```
![image](https://user-images.githubusercontent.com/1804755/97088174-b2a92380-1661-11eb-92e0-b6c100ae938f.png)
![image](https://user-images.githubusercontent.com/1804755/97091587-77155600-166f-11eb-816a-6b55e1c9f597.png)
no error message

## Compile result is a `simple` file and I added a `test.mkv` file for testing purpose (download with youtube-dl https://www.youtube.com/watch?v=-6TncNpzKsA)
![image](https://user-images.githubusercontent.com/1804755/97088142-8097c180-1661-11eb-81fb-13b053ebb214.png)

## Here is output when I run `./simple test.mkv`
![image](https://user-images.githubusercontent.com/1804755/97088153-88576600-1661-11eb-93fc-5877a5a08388.png)

## Zoom in
![image](https://user-images.githubusercontent.com/1804755/97088158-8b525680-1661-11eb-927a-8b346b930755.png)
## The problem here is nothing happen, it should play video

# What I expect to happen (when running `./simple test.mkv`)
It play video correctly just like running `mpv test.mkv`command
Like this:  
![image](https://user-images.githubusercontent.com/1804755/97088260-41b63b80-1662-11eb-972e-3e41aaf2cadd.png)

![image](https://user-images.githubusercontent.com/1804755/97088258-3cf18780-1662-11eb-85b7-fcb26e3d8aeb.png)

# What actually happen
nothing happen

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/97088200-e97f3980-1661-11eb-84f7-029fbbc669ee.png)

Seem like this example need some update, since it was written 5 years ago

**Comment by 1c7** [comment]
Thank you in advance!

**Comment by CounterPillow** [comment]
Works fine for me on Linux, the next event you should be seeing is `event: file-loaded`.

@Akemi can you test this on macOS?

**Comment by 1c7** [comment]
Yes I am using macOS, it doesn't work on my machine.
![image](https://user-images.githubusercontent.com/1804755/97091125-ff91f780-166b-11eb-8f3d-d66d9a65af5e.png)

**Comment by 1c7** [comment]
## A quick update:
* `cocoa/`: work fine (on my machine)
* `cocoa-rendergl`/ work fine
* `sdl/` work fine
* `simple/` **doesn't work**
* I didn't test rest of folder because I don't need them

**Comment by Akemi** [comment]
seems like it's hanging at initialising the old cocoa backend (https://0x0.st/ikT9.log). the old backend is deprecated and isn't really meant to be used anymore. i also believe the new cocoa-cb backend is also not meant to be used like this, since it's just using libmpv internally. imo currently the simple example is just not meant to be used on macOS because of missing support due to technicalities. 

i don't really feel like finding the reason of the deadlock in the old cocoa backend, since it's deprecated. i also made sure it's not deadlocking because of anything swift related, i tried it with disabling swift entirely. an audio only file works correctly.

**Comment by Akemi** [comment]
my bet is on the main thread problem with cocoa gui stuff and that example never worked. see #29.

**Comment by 1c7** [comment]
@Akemi  Thank you
