### ISSUE TITLE
Hey is there a way to launch qt example in fullscreen mode

### ISSUE THREAD

**Issue by keshavbhatt** [mpv-player/mpv-examples#6]
a way to launch qt example in fullscreen mode with double click or something like a toggle shortcut ???
Thanks i really need this for my project. ty

**Comment by wm4** [comment]
That's a Qt question and has really nothing to do with mpv or how to integrate it. For fullscreen, you'd simply place the mpv renderer (whichever you use) on a Qt fullscreen window. In QtQuick, it can be done with `setVisibility` + the fullscreen enum.
