### ISSUE TITLE
simple-streamcb not working due to unimplemented size_fn callback

### ISSUE THREAD

**Issue by wphilips** [mpv-player/mpv-examples#7]
When running the example as follows:
 ./simple-streamcb  /mnt/tvheadend/Holby\ City.ts 
navigating with arrow keys does not work.
 seek_fn is always called with an offset 0. This is dues to 
size_fn not being implemented in  the example. 
This makes the example less useful.

Adding the following  size_fn makes the example work as expected:

static int64_t size_fn(void *cookie)
{
	FILE *fp = cookie;
	struct stat st;
	if(fstat(fileno(fp),&st)) {
		return  MPV_ERROR_UNSUPPORTED;
	}
	return st.st_size;
}

This callback needs to be activated by adding a line
info->size_fn = size_fn;
in the function open_fn.

**Comment by wm4** [comment]
I guess that would work. Please make a PR (and fix the whitespace use of your snipped).
